/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from '@subql/contract-sdk/typechain/common.js';

export declare namespace DelegationPool {
  export type UnbondRequestStruct = {
    amount: BigNumberish;
    startTime: BigNumberish;
    completed: boolean;
  };

  export type UnbondRequestStructOutput = [BigNumber, BigNumber, boolean] & {
    amount: BigNumber;
    startTime: BigNumber;
    completed: boolean;
  };
}

export interface DelegationPoolInterface extends utils.Interface {
  functions: {
    'accumulatedFees()': FunctionFragment;
    'accumulatedUnbondFees()': FunctionFragment;
    'activeIndexers(uint256)': FunctionFragment;
    'allowance(address,address)': FunctionFragment;
    'approve(address,uint256)': FunctionFragment;
    'autoCompound()': FunctionFragment;
    'availableAssets()': FunctionFragment;
    'balanceOf(address)': FunctionFragment;
    'collectAllFees()': FunctionFragment;
    'collectFees(uint256)': FunctionFragment;
    'currentEraSharePrice()': FunctionFragment;
    'decimals()': FunctionFragment;
    'decreaseAllowance(address,uint256)': FunctionFragment;
    'delegate(uint256)': FunctionFragment;
    'expectedUnbondFees()': FunctionFragment;
    'feePerMill()': FunctionFragment;
    'getAccumulatedFees()': FunctionFragment;
    'getActiveIndexers()': FunctionFragment;
    'getActiveIndexersCount()': FunctionFragment;
    'getCurrentSharePrice()': FunctionFragment;
    'getDelegatedToIndexer(address)': FunctionFragment;
    'getDelegationAmount(address)': FunctionFragment;
    'getFeeRate()': FunctionFragment;
    'getLastPriceUpdateEra()': FunctionFragment;
    'getPendingRewards()': FunctionFragment;
    'getPendingUnbonds(address)': FunctionFragment;
    'getTotalAssets()': FunctionFragment;
    'increaseAllowance(address,uint256)': FunctionFragment;
    'initialize(address,uint256)': FunctionFragment;
    'isActiveIndexer(address)': FunctionFragment;
    'lastPriceUpdateEra()': FunctionFragment;
    'managerCancelUnbonding(uint256)': FunctionFragment;
    'managerDelegate(address,uint256)': FunctionFragment;
    'managerRedelegate(address,address,uint256)': FunctionFragment;
    'managerUndelegate(address,uint256)': FunctionFragment;
    'managerWithdraw()': FunctionFragment;
    'name()': FunctionFragment;
    'owner()': FunctionFragment;
    'pendingUndelegationsForUsers()': FunctionFragment;
    'previewDeposit(uint256)': FunctionFragment;
    'previewWithdraw(uint256)': FunctionFragment;
    'renounceOwnership()': FunctionFragment;
    'setFeeRate(uint256)': FunctionFragment;
    'settings()': FunctionFragment;
    'symbol()': FunctionFragment;
    'totalAssetsAtLastUpdate()': FunctionFragment;
    'totalSharesAtLastUpdate()': FunctionFragment;
    'totalSupply()': FunctionFragment;
    'transfer(address,uint256)': FunctionFragment;
    'transferFrom(address,address,uint256)': FunctionFragment;
    'transferOwnership(address)': FunctionFragment;
    'unbondingRequests(address,uint256)': FunctionFragment;
    'undelegate(uint256)': FunctionFragment;
    'updateSettings(address)': FunctionFragment;
    'withdraw()': FunctionFragment;
    'withdrawnLength(address)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'accumulatedFees'
      | 'accumulatedUnbondFees'
      | 'activeIndexers'
      | 'allowance'
      | 'approve'
      | 'autoCompound'
      | 'availableAssets'
      | 'balanceOf'
      | 'collectAllFees'
      | 'collectFees'
      | 'currentEraSharePrice'
      | 'decimals'
      | 'decreaseAllowance'
      | 'delegate'
      | 'expectedUnbondFees'
      | 'feePerMill'
      | 'getAccumulatedFees'
      | 'getActiveIndexers'
      | 'getActiveIndexersCount'
      | 'getCurrentSharePrice'
      | 'getDelegatedToIndexer'
      | 'getDelegationAmount'
      | 'getFeeRate'
      | 'getLastPriceUpdateEra'
      | 'getPendingRewards'
      | 'getPendingUnbonds'
      | 'getTotalAssets'
      | 'increaseAllowance'
      | 'initialize'
      | 'isActiveIndexer'
      | 'lastPriceUpdateEra'
      | 'managerCancelUnbonding'
      | 'managerDelegate'
      | 'managerRedelegate'
      | 'managerUndelegate'
      | 'managerWithdraw'
      | 'name'
      | 'owner'
      | 'pendingUndelegationsForUsers'
      | 'previewDeposit'
      | 'previewWithdraw'
      | 'renounceOwnership'
      | 'setFeeRate'
      | 'settings'
      | 'symbol'
      | 'totalAssetsAtLastUpdate'
      | 'totalSharesAtLastUpdate'
      | 'totalSupply'
      | 'transfer'
      | 'transferFrom'
      | 'transferOwnership'
      | 'unbondingRequests'
      | 'undelegate'
      | 'updateSettings'
      | 'withdraw'
      | 'withdrawnLength',
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'accumulatedFees', values?: undefined): string;
  encodeFunctionData(functionFragment: 'accumulatedUnbondFees', values?: undefined): string;
  encodeFunctionData(functionFragment: 'activeIndexers', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'allowance', values: [string, string]): string;
  encodeFunctionData(functionFragment: 'approve', values: [string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'autoCompound', values?: undefined): string;
  encodeFunctionData(functionFragment: 'availableAssets', values?: undefined): string;
  encodeFunctionData(functionFragment: 'balanceOf', values: [string]): string;
  encodeFunctionData(functionFragment: 'collectAllFees', values?: undefined): string;
  encodeFunctionData(functionFragment: 'collectFees', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'currentEraSharePrice', values?: undefined): string;
  encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
  encodeFunctionData(functionFragment: 'decreaseAllowance', values: [string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'delegate', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'expectedUnbondFees', values?: undefined): string;
  encodeFunctionData(functionFragment: 'feePerMill', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getAccumulatedFees', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getActiveIndexers', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getActiveIndexersCount', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getCurrentSharePrice', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getDelegatedToIndexer', values: [string]): string;
  encodeFunctionData(functionFragment: 'getDelegationAmount', values: [string]): string;
  encodeFunctionData(functionFragment: 'getFeeRate', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getLastPriceUpdateEra', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getPendingRewards', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getPendingUnbonds', values: [string]): string;
  encodeFunctionData(functionFragment: 'getTotalAssets', values?: undefined): string;
  encodeFunctionData(functionFragment: 'increaseAllowance', values: [string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'initialize', values: [string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'isActiveIndexer', values: [string]): string;
  encodeFunctionData(functionFragment: 'lastPriceUpdateEra', values?: undefined): string;
  encodeFunctionData(functionFragment: 'managerCancelUnbonding', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'managerDelegate', values: [string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'managerRedelegate', values: [string, string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'managerUndelegate', values: [string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'managerWithdraw', values?: undefined): string;
  encodeFunctionData(functionFragment: 'name', values?: undefined): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(functionFragment: 'pendingUndelegationsForUsers', values?: undefined): string;
  encodeFunctionData(functionFragment: 'previewDeposit', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'previewWithdraw', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
  encodeFunctionData(functionFragment: 'setFeeRate', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'settings', values?: undefined): string;
  encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
  encodeFunctionData(functionFragment: 'totalAssetsAtLastUpdate', values?: undefined): string;
  encodeFunctionData(functionFragment: 'totalSharesAtLastUpdate', values?: undefined): string;
  encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
  encodeFunctionData(functionFragment: 'transfer', values: [string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'transferFrom', values: [string, string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'transferOwnership', values: [string]): string;
  encodeFunctionData(functionFragment: 'unbondingRequests', values: [string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'undelegate', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'updateSettings', values: [string]): string;
  encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;
  encodeFunctionData(functionFragment: 'withdrawnLength', values: [string]): string;

  decodeFunctionResult(functionFragment: 'accumulatedFees', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'accumulatedUnbondFees', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'activeIndexers', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'autoCompound', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'availableAssets', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'collectAllFees', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'collectFees', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'currentEraSharePrice', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'decreaseAllowance', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'delegate', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'expectedUnbondFees', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'feePerMill', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getAccumulatedFees', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getActiveIndexers', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getActiveIndexersCount', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getCurrentSharePrice', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getDelegatedToIndexer', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getDelegationAmount', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getFeeRate', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getLastPriceUpdateEra', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getPendingRewards', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getPendingUnbonds', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getTotalAssets', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'increaseAllowance', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'isActiveIndexer', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'lastPriceUpdateEra', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'managerCancelUnbonding', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'managerDelegate', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'managerRedelegate', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'managerUndelegate', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'managerWithdraw', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'pendingUndelegationsForUsers', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'previewDeposit', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'previewWithdraw', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setFeeRate', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'settings', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'totalAssetsAtLastUpdate', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'totalSharesAtLastUpdate', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'unbondingRequests', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'undelegate', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'updateSettings', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'withdrawnLength', data: BytesLike): Result;

  events: {
    'Approval(address,address,uint256)': EventFragment;
    'Delegated(address,uint256,uint256)': EventFragment;
    'FeeRateUpdated(uint256)': EventFragment;
    'FeesCollected(address,uint256)': EventFragment;
    'FeesDeducted(uint256,uint256)': EventFragment;
    'Initialized(uint8)': EventFragment;
    'ManagerDelegated(address,uint256)': EventFragment;
    'ManagerRedelegated(address,address,uint256)': EventFragment;
    'ManagerUndelegated(address,uint256)': EventFragment;
    'OwnershipTransferred(address,address)': EventFragment;
    'RewardsCompounded(uint256)': EventFragment;
    'SharePriceUpdated(uint256,uint256)': EventFragment;
    'Transfer(address,address,uint256)': EventFragment;
    'UnbondFeeTracked(uint256,uint256)': EventFragment;
    'UndelegationRequired(address,uint256,uint256)': EventFragment;
    'UndelegationStarted(address,uint256,uint256)': EventFragment;
    'Withdrawn(address,uint256)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'Approval'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Delegated'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'FeeRateUpdated'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'FeesCollected'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'FeesDeducted'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Initialized'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'ManagerDelegated'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'ManagerRedelegated'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'ManagerUndelegated'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'RewardsCompounded'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'SharePriceUpdated'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Transfer'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'UnbondFeeTracked'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'UndelegationRequired'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'UndelegationStarted'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Withdrawn'): EventFragment;
}

export interface ApprovalEventObject {
  owner: string;
  spender: string;
  value: BigNumber;
}
export type ApprovalEvent = TypedEvent<[string, string, BigNumber], ApprovalEventObject>;

export type ApprovalEventFilter = TypedEventFilter<ApprovalEvent>;

export interface DelegatedEventObject {
  user: string;
  amount: BigNumber;
  shares: BigNumber;
}
export type DelegatedEvent = TypedEvent<[string, BigNumber, BigNumber], DelegatedEventObject>;

export type DelegatedEventFilter = TypedEventFilter<DelegatedEvent>;

export interface FeeRateUpdatedEventObject {
  newFeePerMill: BigNumber;
}
export type FeeRateUpdatedEvent = TypedEvent<[BigNumber], FeeRateUpdatedEventObject>;

export type FeeRateUpdatedEventFilter = TypedEventFilter<FeeRateUpdatedEvent>;

export interface FeesCollectedEventObject {
  controller: string;
  amount: BigNumber;
}
export type FeesCollectedEvent = TypedEvent<[string, BigNumber], FeesCollectedEventObject>;

export type FeesCollectedEventFilter = TypedEventFilter<FeesCollectedEvent>;

export interface FeesDeductedEventObject {
  rewardAmount: BigNumber;
  feeAmount: BigNumber;
}
export type FeesDeductedEvent = TypedEvent<[BigNumber, BigNumber], FeesDeductedEventObject>;

export type FeesDeductedEventFilter = TypedEventFilter<FeesDeductedEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface ManagerDelegatedEventObject {
  indexer: string;
  amount: BigNumber;
}
export type ManagerDelegatedEvent = TypedEvent<[string, BigNumber], ManagerDelegatedEventObject>;

export type ManagerDelegatedEventFilter = TypedEventFilter<ManagerDelegatedEvent>;

export interface ManagerRedelegatedEventObject {
  fromIndexer: string;
  toIndexer: string;
  amount: BigNumber;
}
export type ManagerRedelegatedEvent = TypedEvent<[string, string, BigNumber], ManagerRedelegatedEventObject>;

export type ManagerRedelegatedEventFilter = TypedEventFilter<ManagerRedelegatedEvent>;

export interface ManagerUndelegatedEventObject {
  indexer: string;
  amount: BigNumber;
}
export type ManagerUndelegatedEvent = TypedEvent<[string, BigNumber], ManagerUndelegatedEventObject>;

export type ManagerUndelegatedEventFilter = TypedEventFilter<ManagerUndelegatedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<[string, string], OwnershipTransferredEventObject>;

export type OwnershipTransferredEventFilter = TypedEventFilter<OwnershipTransferredEvent>;

export interface RewardsCompoundedEventObject {
  totalRewards: BigNumber;
}
export type RewardsCompoundedEvent = TypedEvent<[BigNumber], RewardsCompoundedEventObject>;

export type RewardsCompoundedEventFilter = TypedEventFilter<RewardsCompoundedEvent>;

export interface SharePriceUpdatedEventObject {
  era: BigNumber;
  pricePerShare: BigNumber;
}
export type SharePriceUpdatedEvent = TypedEvent<[BigNumber, BigNumber], SharePriceUpdatedEventObject>;

export type SharePriceUpdatedEventFilter = TypedEventFilter<SharePriceUpdatedEvent>;

export interface TransferEventObject {
  from: string;
  to: string;
  value: BigNumber;
}
export type TransferEvent = TypedEvent<[string, string, BigNumber], TransferEventObject>;

export type TransferEventFilter = TypedEventFilter<TransferEvent>;

export interface UnbondFeeTrackedEventObject {
  amount: BigNumber;
  totalExpected: BigNumber;
}
export type UnbondFeeTrackedEvent = TypedEvent<[BigNumber, BigNumber], UnbondFeeTrackedEventObject>;

export type UnbondFeeTrackedEventFilter = TypedEventFilter<UnbondFeeTrackedEvent>;

export interface UndelegationRequiredEventObject {
  user: string;
  requiredAmount: BigNumber;
  remainingAmount: BigNumber;
}
export type UndelegationRequiredEvent = TypedEvent<[string, BigNumber, BigNumber], UndelegationRequiredEventObject>;

export type UndelegationRequiredEventFilter = TypedEventFilter<UndelegationRequiredEvent>;

export interface UndelegationStartedEventObject {
  user: string;
  shares: BigNumber;
  amount: BigNumber;
}
export type UndelegationStartedEvent = TypedEvent<[string, BigNumber, BigNumber], UndelegationStartedEventObject>;

export type UndelegationStartedEventFilter = TypedEventFilter<UndelegationStartedEvent>;

export interface WithdrawnEventObject {
  user: string;
  amount: BigNumber;
}
export type WithdrawnEvent = TypedEvent<[string, BigNumber], WithdrawnEventObject>;

export type WithdrawnEventFilter = TypedEventFilter<WithdrawnEvent>;

export interface DelegationPool extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DelegationPoolInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    accumulatedFees(overrides?: CallOverrides): Promise<[BigNumber]>;

    accumulatedUnbondFees(overrides?: CallOverrides): Promise<[BigNumber]>;

    activeIndexers(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    allowance(owner: string, spender: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    autoCompound(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

    availableAssets(overrides?: CallOverrides): Promise<[BigNumber]>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    collectAllFees(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

    collectFees(_amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

    currentEraSharePrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    decimals(overrides?: CallOverrides): Promise<[number]>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    delegate(_amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

    expectedUnbondFees(overrides?: CallOverrides): Promise<[BigNumber]>;

    feePerMill(overrides?: CallOverrides): Promise<[BigNumber]>;

    getAccumulatedFees(overrides?: CallOverrides): Promise<[BigNumber]>;

    getActiveIndexers(overrides?: CallOverrides): Promise<[string[]]>;

    getActiveIndexersCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    getCurrentSharePrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    getDelegatedToIndexer(_indexer: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    getDelegationAmount(_user: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    getFeeRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    getLastPriceUpdateEra(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPendingRewards(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPendingUnbonds(_user: string, overrides?: CallOverrides): Promise<[DelegationPool.UnbondRequestStructOutput[]]>;

    getTotalAssets(overrides?: CallOverrides): Promise<[BigNumber]>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    initialize(
      _settings: string,
      _feePerMill: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    isActiveIndexer(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    lastPriceUpdateEra(overrides?: CallOverrides): Promise<[BigNumber]>;

    managerCancelUnbonding(
      unbondReqId: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    managerDelegate(
      _runner: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    managerRedelegate(
      _fromRunner: string,
      _toRunner: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    managerUndelegate(
      _runner: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    managerWithdraw(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

    name(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pendingUndelegationsForUsers(overrides?: CallOverrides): Promise<[BigNumber]>;

    previewDeposit(_amount: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>;

    previewWithdraw(_shares: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>;

    renounceOwnership(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

    setFeeRate(_feePerMill: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

    settings(overrides?: CallOverrides): Promise<[string]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    totalAssetsAtLastUpdate(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalSharesAtLastUpdate(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    transfer(to: string, amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

    transferFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    transferOwnership(newOwner: string, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

    unbondingRequests(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        amount: BigNumber;
        startTime: BigNumber;
        completed: boolean;
      }
    >;

    undelegate(shareAmount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

    updateSettings(_settings: string, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

    withdraw(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

    withdrawnLength(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  accumulatedFees(overrides?: CallOverrides): Promise<BigNumber>;

  accumulatedUnbondFees(overrides?: CallOverrides): Promise<BigNumber>;

  activeIndexers(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  allowance(owner: string, spender: string, overrides?: CallOverrides): Promise<BigNumber>;

  approve(
    spender: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  autoCompound(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  availableAssets(overrides?: CallOverrides): Promise<BigNumber>;

  balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

  collectAllFees(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  collectFees(_amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  currentEraSharePrice(overrides?: CallOverrides): Promise<BigNumber>;

  decimals(overrides?: CallOverrides): Promise<number>;

  decreaseAllowance(
    spender: string,
    subtractedValue: BigNumberish,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  delegate(_amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  expectedUnbondFees(overrides?: CallOverrides): Promise<BigNumber>;

  feePerMill(overrides?: CallOverrides): Promise<BigNumber>;

  getAccumulatedFees(overrides?: CallOverrides): Promise<BigNumber>;

  getActiveIndexers(overrides?: CallOverrides): Promise<string[]>;

  getActiveIndexersCount(overrides?: CallOverrides): Promise<BigNumber>;

  getCurrentSharePrice(overrides?: CallOverrides): Promise<BigNumber>;

  getDelegatedToIndexer(_indexer: string, overrides?: CallOverrides): Promise<BigNumber>;

  getDelegationAmount(_user: string, overrides?: CallOverrides): Promise<BigNumber>;

  getFeeRate(overrides?: CallOverrides): Promise<BigNumber>;

  getLastPriceUpdateEra(overrides?: CallOverrides): Promise<BigNumber>;

  getPendingRewards(overrides?: CallOverrides): Promise<BigNumber>;

  getPendingUnbonds(_user: string, overrides?: CallOverrides): Promise<DelegationPool.UnbondRequestStructOutput[]>;

  getTotalAssets(overrides?: CallOverrides): Promise<BigNumber>;

  increaseAllowance(
    spender: string,
    addedValue: BigNumberish,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  initialize(
    _settings: string,
    _feePerMill: BigNumberish,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  isActiveIndexer(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  lastPriceUpdateEra(overrides?: CallOverrides): Promise<BigNumber>;

  managerCancelUnbonding(
    unbondReqId: BigNumberish,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  managerDelegate(
    _runner: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  managerRedelegate(
    _fromRunner: string,
    _toRunner: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  managerUndelegate(
    _runner: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  managerWithdraw(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  name(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  pendingUndelegationsForUsers(overrides?: CallOverrides): Promise<BigNumber>;

  previewDeposit(_amount: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  previewWithdraw(_shares: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  renounceOwnership(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  setFeeRate(_feePerMill: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  settings(overrides?: CallOverrides): Promise<string>;

  symbol(overrides?: CallOverrides): Promise<string>;

  totalAssetsAtLastUpdate(overrides?: CallOverrides): Promise<BigNumber>;

  totalSharesAtLastUpdate(overrides?: CallOverrides): Promise<BigNumber>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  transfer(to: string, amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  transferFrom(
    from: string,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  transferOwnership(newOwner: string, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  unbondingRequests(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<
    [BigNumber, BigNumber, boolean] & {
      amount: BigNumber;
      startTime: BigNumber;
      completed: boolean;
    }
  >;

  undelegate(shareAmount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  updateSettings(_settings: string, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  withdraw(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  withdrawnLength(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    accumulatedFees(overrides?: CallOverrides): Promise<BigNumber>;

    accumulatedUnbondFees(overrides?: CallOverrides): Promise<BigNumber>;

    activeIndexers(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    allowance(owner: string, spender: string, overrides?: CallOverrides): Promise<BigNumber>;

    approve(spender: string, amount: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    autoCompound(overrides?: CallOverrides): Promise<void>;

    availableAssets(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    collectAllFees(overrides?: CallOverrides): Promise<void>;

    collectFees(_amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    currentEraSharePrice(overrides?: CallOverrides): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<number>;

    decreaseAllowance(spender: string, subtractedValue: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    delegate(_amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    expectedUnbondFees(overrides?: CallOverrides): Promise<BigNumber>;

    feePerMill(overrides?: CallOverrides): Promise<BigNumber>;

    getAccumulatedFees(overrides?: CallOverrides): Promise<BigNumber>;

    getActiveIndexers(overrides?: CallOverrides): Promise<string[]>;

    getActiveIndexersCount(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentSharePrice(overrides?: CallOverrides): Promise<BigNumber>;

    getDelegatedToIndexer(_indexer: string, overrides?: CallOverrides): Promise<BigNumber>;

    getDelegationAmount(_user: string, overrides?: CallOverrides): Promise<BigNumber>;

    getFeeRate(overrides?: CallOverrides): Promise<BigNumber>;

    getLastPriceUpdateEra(overrides?: CallOverrides): Promise<BigNumber>;

    getPendingRewards(overrides?: CallOverrides): Promise<BigNumber>;

    getPendingUnbonds(_user: string, overrides?: CallOverrides): Promise<DelegationPool.UnbondRequestStructOutput[]>;

    getTotalAssets(overrides?: CallOverrides): Promise<BigNumber>;

    increaseAllowance(spender: string, addedValue: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    initialize(_settings: string, _feePerMill: BigNumberish, overrides?: CallOverrides): Promise<void>;

    isActiveIndexer(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    lastPriceUpdateEra(overrides?: CallOverrides): Promise<BigNumber>;

    managerCancelUnbonding(unbondReqId: BigNumberish, overrides?: CallOverrides): Promise<void>;

    managerDelegate(_runner: string, _amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    managerRedelegate(
      _fromRunner: string,
      _toRunner: string,
      _amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    managerUndelegate(_runner: string, _amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    managerWithdraw(overrides?: CallOverrides): Promise<void>;

    name(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    pendingUndelegationsForUsers(overrides?: CallOverrides): Promise<BigNumber>;

    previewDeposit(_amount: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    previewWithdraw(_shares: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setFeeRate(_feePerMill: BigNumberish, overrides?: CallOverrides): Promise<void>;

    settings(overrides?: CallOverrides): Promise<string>;

    symbol(overrides?: CallOverrides): Promise<string>;

    totalAssetsAtLastUpdate(overrides?: CallOverrides): Promise<BigNumber>;

    totalSharesAtLastUpdate(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(to: string, amount: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    transferFrom(from: string, to: string, amount: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    transferOwnership(newOwner: string, overrides?: CallOverrides): Promise<void>;

    unbondingRequests(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        amount: BigNumber;
        startTime: BigNumber;
        completed: boolean;
      }
    >;

    undelegate(shareAmount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    updateSettings(_settings: string, overrides?: CallOverrides): Promise<void>;

    withdraw(overrides?: CallOverrides): Promise<void>;

    withdrawnLength(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    'Approval(address,address,uint256)'(
      owner?: string | null,
      spender?: string | null,
      value?: null,
    ): ApprovalEventFilter;
    Approval(owner?: string | null, spender?: string | null, value?: null): ApprovalEventFilter;

    'Delegated(address,uint256,uint256)'(user?: string | null, amount?: null, shares?: null): DelegatedEventFilter;
    Delegated(user?: string | null, amount?: null, shares?: null): DelegatedEventFilter;

    'FeeRateUpdated(uint256)'(newFeePerMill?: null): FeeRateUpdatedEventFilter;
    FeeRateUpdated(newFeePerMill?: null): FeeRateUpdatedEventFilter;

    'FeesCollected(address,uint256)'(controller?: string | null, amount?: null): FeesCollectedEventFilter;
    FeesCollected(controller?: string | null, amount?: null): FeesCollectedEventFilter;

    'FeesDeducted(uint256,uint256)'(rewardAmount?: null, feeAmount?: null): FeesDeductedEventFilter;
    FeesDeducted(rewardAmount?: null, feeAmount?: null): FeesDeductedEventFilter;

    'Initialized(uint8)'(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    'ManagerDelegated(address,uint256)'(indexer?: string | null, amount?: null): ManagerDelegatedEventFilter;
    ManagerDelegated(indexer?: string | null, amount?: null): ManagerDelegatedEventFilter;

    'ManagerRedelegated(address,address,uint256)'(
      fromIndexer?: string | null,
      toIndexer?: string | null,
      amount?: null,
    ): ManagerRedelegatedEventFilter;
    ManagerRedelegated(
      fromIndexer?: string | null,
      toIndexer?: string | null,
      amount?: null,
    ): ManagerRedelegatedEventFilter;

    'ManagerUndelegated(address,uint256)'(indexer?: string | null, amount?: null): ManagerUndelegatedEventFilter;
    ManagerUndelegated(indexer?: string | null, amount?: null): ManagerUndelegatedEventFilter;

    'OwnershipTransferred(address,address)'(
      previousOwner?: string | null,
      newOwner?: string | null,
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(previousOwner?: string | null, newOwner?: string | null): OwnershipTransferredEventFilter;

    'RewardsCompounded(uint256)'(totalRewards?: null): RewardsCompoundedEventFilter;
    RewardsCompounded(totalRewards?: null): RewardsCompoundedEventFilter;

    'SharePriceUpdated(uint256,uint256)'(era?: BigNumberish | null, pricePerShare?: null): SharePriceUpdatedEventFilter;
    SharePriceUpdated(era?: BigNumberish | null, pricePerShare?: null): SharePriceUpdatedEventFilter;

    'Transfer(address,address,uint256)'(from?: string | null, to?: string | null, value?: null): TransferEventFilter;
    Transfer(from?: string | null, to?: string | null, value?: null): TransferEventFilter;

    'UnbondFeeTracked(uint256,uint256)'(amount?: null, totalExpected?: null): UnbondFeeTrackedEventFilter;
    UnbondFeeTracked(amount?: null, totalExpected?: null): UnbondFeeTrackedEventFilter;

    'UndelegationRequired(address,uint256,uint256)'(
      user?: string | null,
      requiredAmount?: null,
      remainingAmount?: null,
    ): UndelegationRequiredEventFilter;
    UndelegationRequired(
      user?: string | null,
      requiredAmount?: null,
      remainingAmount?: null,
    ): UndelegationRequiredEventFilter;

    'UndelegationStarted(address,uint256,uint256)'(
      user?: string | null,
      shares?: null,
      amount?: null,
    ): UndelegationStartedEventFilter;
    UndelegationStarted(user?: string | null, shares?: null, amount?: null): UndelegationStartedEventFilter;

    'Withdrawn(address,uint256)'(user?: string | null, amount?: null): WithdrawnEventFilter;
    Withdrawn(user?: string | null, amount?: null): WithdrawnEventFilter;
  };

  estimateGas: {
    accumulatedFees(overrides?: CallOverrides): Promise<BigNumber>;

    accumulatedUnbondFees(overrides?: CallOverrides): Promise<BigNumber>;

    activeIndexers(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    allowance(owner: string, spender: string, overrides?: CallOverrides): Promise<BigNumber>;

    approve(spender: string, amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    autoCompound(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    availableAssets(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    collectAllFees(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    collectFees(_amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    currentEraSharePrice(overrides?: CallOverrides): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    delegate(_amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    expectedUnbondFees(overrides?: CallOverrides): Promise<BigNumber>;

    feePerMill(overrides?: CallOverrides): Promise<BigNumber>;

    getAccumulatedFees(overrides?: CallOverrides): Promise<BigNumber>;

    getActiveIndexers(overrides?: CallOverrides): Promise<BigNumber>;

    getActiveIndexersCount(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentSharePrice(overrides?: CallOverrides): Promise<BigNumber>;

    getDelegatedToIndexer(_indexer: string, overrides?: CallOverrides): Promise<BigNumber>;

    getDelegationAmount(_user: string, overrides?: CallOverrides): Promise<BigNumber>;

    getFeeRate(overrides?: CallOverrides): Promise<BigNumber>;

    getLastPriceUpdateEra(overrides?: CallOverrides): Promise<BigNumber>;

    getPendingRewards(overrides?: CallOverrides): Promise<BigNumber>;

    getPendingUnbonds(_user: string, overrides?: CallOverrides): Promise<BigNumber>;

    getTotalAssets(overrides?: CallOverrides): Promise<BigNumber>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    initialize(
      _settings: string,
      _feePerMill: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    isActiveIndexer(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    lastPriceUpdateEra(overrides?: CallOverrides): Promise<BigNumber>;

    managerCancelUnbonding(unbondReqId: BigNumberish, overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    managerDelegate(
      _runner: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    managerRedelegate(
      _fromRunner: string,
      _toRunner: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    managerUndelegate(
      _runner: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    managerWithdraw(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pendingUndelegationsForUsers(overrides?: CallOverrides): Promise<BigNumber>;

    previewDeposit(_amount: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    previewWithdraw(_shares: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    setFeeRate(_feePerMill: BigNumberish, overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    settings(overrides?: CallOverrides): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    totalAssetsAtLastUpdate(overrides?: CallOverrides): Promise<BigNumber>;

    totalSharesAtLastUpdate(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(to: string, amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    transferFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    transferOwnership(newOwner: string, overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    unbondingRequests(arg0: string, arg1: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    undelegate(shareAmount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    updateSettings(_settings: string, overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    withdraw(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    withdrawnLength(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    accumulatedFees(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    accumulatedUnbondFees(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    activeIndexers(arg0: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    allowance(owner: string, spender: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    autoCompound(overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>;

    availableAssets(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    collectAllFees(overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>;

    collectFees(_amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>;

    currentEraSharePrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    delegate(_amount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>;

    expectedUnbondFees(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feePerMill(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAccumulatedFees(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getActiveIndexers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getActiveIndexersCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCurrentSharePrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDelegatedToIndexer(_indexer: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDelegationAmount(_user: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFeeRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLastPriceUpdateEra(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPendingRewards(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPendingUnbonds(_user: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTotalAssets(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    initialize(
      _settings: string,
      _feePerMill: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    isActiveIndexer(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastPriceUpdateEra(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    managerCancelUnbonding(
      unbondReqId: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    managerDelegate(
      _runner: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    managerRedelegate(
      _fromRunner: string,
      _toRunner: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    managerUndelegate(
      _runner: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    managerWithdraw(overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingUndelegationsForUsers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    previewDeposit(_amount: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    previewWithdraw(_shares: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>;

    setFeeRate(_feePerMill: BigNumberish, overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>;

    settings(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalAssetsAtLastUpdate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSharesAtLastUpdate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transfer(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    transferFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    transferOwnership(newOwner: string, overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>;

    unbondingRequests(arg0: string, arg1: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    undelegate(shareAmount: BigNumberish, overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>;

    updateSettings(_settings: string, overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>;

    withdraw(overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>;

    withdrawnLength(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
