name: Prod
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      SENTRY_DSN: ${{ secrets.DEV_SENTRY_DSN }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16

      - run: yarn

      - name: Build
        # Disable CI flag so linter warnings aren't treaded as errors
        run: CI=false yarn build

      - name: Deploy Prod
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.KEPLER_PROD_BUCKET }}
          bucket-region: ${{ secrets.S3_PROD_BUCKET_REGION }}
          invalidation: /*
          dist-id: ${{ secrets.CLOUDFRONT_ID_PROD }}
          delete-removed: false
          no-cache: true
          private: true

