name: Mainnet-Prod
on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID_V2 }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_V2 }}
      VITE_SENTRY_DSN: ${{ vars.DEV_SENTRY_DSN }}
      NODE_OPTIONS: --max-old-space-size=32768      
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 18

      - run: yarn

      - name: Build
        # Disable CI flag so linter warnings aren't treated as errors
        run: CI=false yarn build

      - name: Deploy Prod
        uses: reggionick/s3-deploy@v3
        with:
          folder: dist
          bucket: ${{ vars.S3_BUCKET_PROD }}
          bucket-region: ap-northeast-1
          invalidation: /*
          dist-id: ${{ vars.CLOUDFRONT_ID_PROD }}
          delete-removed: false
          private: true
